county_statistics <- read.csv("D:/IB207/county_statistics.csv")
summary(county_statistics)
county_statistics<- na.omit(county_statistics )
library(psych)
library(GPArotation)
typeof(county_statistics$percentage16_Donald_Trump)
county_statistics$percentage16_Donald_Trump<- as.numeric(county_statistics$percentage16_Donald_Trump)
county_statistics$percentage16_Hillary_Clinton<- as.numeric(county_statistics$percentage16_Hillary_Clinton)
county_statistics$total_votes16<- as.numeric(county_statistics$total_votes16)
county_statistics$votes16_Donald_Trump<- as.numeric(county_statistics$votes16_Donald_Trump)
county_statistics$votes16_Hillary_Clinton<- as.numeric(county_statistics$votes16_Hillary_Clinton)
county_statistics$percentage20_Donald_Trump<- as.numeric(county_statistics$percentage20_Donald_Trump)
county_statistics$percentage20_Joe_Biden<- as.numeric(county_statistics$percentage20_Joe_Biden)
county_statistics$total_votes20<- as.numeric(county_statistics$total_votes20)
county_statistics$votes20_Donald_Trump<- as.numeric(county_statistics$votes20_Donald_Trump)
county_statistics$votes20_Joe_Biden<- as.numeric(county_statistics$votes20_Joe_Biden)
county_statistics$lat<- as.numeric(county_statistics$lat)
county_statistics$long<- as.numeric(county_statistics$long)
county_statistics$cases<- as.numeric(county_statistics$cases)
county_statistics$deaths<- as.numeric(county_statistics$deaths)
county_statistics$TotalPop<- as.numeric(county_statistics$TotalPop)
county_statistics$Men<- as.numeric(county_statistics$Men)
county_statistics$Women<- as.numeric(county_statistics$Women)
county_statistics$Hispanic<- as.numeric(county_statistics$Hispanic)
county_statistics$White<- as.numeric(county_statistics$White)
county_statistics$Black<- as.numeric(county_statistics$Black)
county_statistics$Native<- as.numeric(county_statistics$Native)
county_statistics$Asian<- as.numeric(county_statistics$Asian)
county_statistics$Pacific<- as.numeric(county_statistics$Pacific)
county_statistics$VotingAgeCitizen<- as.numeric(county_statistics$VotingAgeCitizen)
county_statistics$Income<- as.numeric(county_statistics$Income)
county_statistics$IncomeErr<- as.numeric(county_statistics$IncomeErr)
county_statistics$IncomePerCap<- as.numeric(county_statistics$IncomePerCap)
county_statistics$IncomePerCapErr<- as.numeric(county_statistics$IncomePerCapErr)
county_statistics$Poverty<- as.numeric(county_statistics$Poverty)
county_statistics$Professional<- as.numeric(county_statistics$Professional)
county_statistics$Service<- as.numeric(county_statistics$Service)
county_statistics$Office<- as.numeric(county_statistics$Office)
county_statistics$Construction<- as.numeric(county_statistics$Construction)
county_statistics$Production<- as.numeric(county_statistics$Production)
county_statistics$Drive<- as.numeric(county_statistics$Drive)
county_statistics$Carpool<- as.numeric(county_statistics$Carpool)
county_statistics$Transit<- as.numeric(county_statistics$Transit)
county_statistics$Walk<- as.numeric(county_statistics$Walk)
county_statistics$OtherTransp<- as.numeric(county_statistics$OtherTransp)
county_statistics$WorkAtHome<- as.numeric(county_statistics$WorkAtHome)
county_statistics$MeanCommute<- as.numeric(county_statistics$MeanCommute)
county_statistics$Employed<- as.numeric(county_statistics$Employed)
county_statistics$PrivateWork<- as.numeric(county_statistics$PrivateWork)
county_statistics$PublicWork<- as.numeric(county_statistics$PublicWork)
county_statistics$SelfEmployed<- as.numeric(county_statistics$SelfEmployed)
county_statistics$FamilyWork<- as.numeric(county_statistics$FamilyWork)
county_statistics$Unemployment<- as.numeric(county_statistics$Unemployment)

mode(county_statistics$percentage16_Donald_Trump)
mode(county_statistics$percentage16_Hillary_Clinton)
mode(county_statistics$total_votes16)
mode(county_statistics$votes16_Donald_Trump)
mode(county_statistics$votes16_Hillary_Clinton)
mode(county_statistics$percentage16_Hillary_Clinton)
mode(county_statistics$percentage20_Donald_Trump)
mode(county_statistics$percentage20_Joe_Biden)
mode(county_statistics$total_votes20)
mode(county_statistics$votes20_Donald_Trump)
mode(county_statistics$votes20_Joe_Biden)
mode(county_statistics$lat)
mode(county_statistics$long)
mode(county_statistics$cases)
mode(county_statistics$deaths)
mode(county_statistics$TotalPop)
mode(county_statistics$Men)
mode(county_statistics$Women)
mode(county_statistics$Hispanic)
mode(county_statistics$White)
mode(county_statistics$Black)
mode(county_statistics$Native)
mode(county_statistics$Asian)
mode(county_statistics$Pacific)
mode(county_statistics$VotingAgeCitizen)
mode(county_statistics$Income)
mode(county_statistics$IncomeErr)
mode(county_statistics$IncomePerCap)
mode(county_statistics$IncomePerCapErr)
mode(county_statistics$Poverty)
mode(county_statistics$ChildPoverty)
mode(county_statistics$Professional)
mode(county_statistics$Service)
mode(county_statistics$Office)
mode(county_statistics$Construction)
mode(county_statistics$Production)
mode(county_statistics$Drive)
mode(county_statistics$Carpool)
mode(county_statistics$Transit)
mode(county_statistics$Walk)
mode(county_statistics$OtherTransp)


statistics<-county_statistics[,c(21:50)]

cormat1= cor(statistics)
cortest.bartlett(cormat1, n=nrow(statistics))

f = factanal(county_statistics[,c(21:50)],factors=5, rotation="none")
print(f,cutoff=.4)
summary(county_statistics[,c(21:50)])
sum(county_statistics$Men)
sum(county_statistics$Women)
fvar = factanal(county_statistics[,c(21:50)],factors=4, rotation="varimax")
print(fvar,cutoff=.4)
plot(fvar, choix  ="var")
factor.plot (fvar)
fpro = factanal(statistics,factors=4, rotation="promax")
print(fpro ,cutoff=.4)
fa.diagram(fvar,simple = FALSE)
scree(f)
fa.parallel(cormat1)
